<?php
/**
 * IndexView.php
 *
 * Sessions: PHP web application to demonstrate how databases
 * are accessed securely
 *
 *
 * @author M Madadi
 * @copyright De Montfort University
 *
 * @package CryptoShow system CMS
 */

/**
 * Represents the view for the login page.
 */
class LoginView
{
    /**
     * @var string The title of the page
     * @var string The content of the page
     * @var string The output of the page
     */
    protected $page_title;
    protected $html_page_content;
    protected $html_page_output;
    /**
     * Constructs a new LoginView object.
     */
    public function __construct()
    {
        $this->page_title = '';
        $this->html_page_content = '';
        $this->html_page_output = '';
    }
    private $login = []; // Declare the property

    /**
     * Sets the login data for the view.
     *
     * @param array $login Login data.
     */
    public function setLogin($login) {
        $this->$login = $login; // Correct variable name
    }
    /**
     * Orchestrates the creation of the login page.
     * It creates the head section, generates page content, and constructs the final HTML output.
     */
    public function createLoginPage()
    {
        $this->createHeadSection();

        $this->createPageContent();

    }
    /**
     * Retrieves the HTML output generated by the view.
     *
     * @return string HTML output generated by the view.
     */
    public function getHtmlOutput(): string
    {
        return $this->html_page_output;
    }
    /**
     * Creates the head section of the login page.
     */
    protected function createHeadSection() {
        $css_path = CSS_PATH;
        $css_filename = 'style.css'; // Assuming you have a main stylesheet named style.css
        $css_index = 'index.css'; // Assuming you have a main stylesheet named style.css
        $backgroundImageURL = "https://madadi.uk/cryptography.jpg";
        $html_output = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
     <title>CryptoShow System | Login </title>
    <meta property="og:title" content="Main" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />
    <link rel="stylesheet" href="{$css_path}{$css_filename}" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap" />
    <link rel="stylesheet" href="{$css_path}{$css_index}" />
    <style>
        html { scroll-behavior: smooth; }
        /* Additional in-line CSS can be placed here */
    </style>
    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Raleway;
        font-size: 18px;
      }

       body {
            font-family: Raleway, sans-serif;
            font-size: 18px;
            font-weight: 400;
            line-height: 1.55;
            color: var(--dl-color-gray-black);
            background-color: var(--dl-color-gray-white);
            background-image: url('$backgroundImageURL');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }
        /* Responsive adjustments */
        @media (max-width: 768px) {
            body {
                /* Adjustments for smaller devices */
                background-position: center center;
            }
        }
        /* For devices narrower than 768px */
        @media (max-width: 768px) {
            body {
                background-size: cover;
            }
        }
    </style>
   
  </head>
  <body>
    <div>
      <div class="home-container">
HTML;

        $this->html_page_output .= $html_output ;
    }
    /**
     * Creates the main content of the login page.
     */
    protected function createPageContent() {
        $message = '';
        if (isset($_SESSION['success_message'])) {
            $message = "<div class='success'>" . $_SESSION['success_message'] . "</div>";
            unset($_SESSION['success_message']);
        }

        $this->html_page_content = <<<HTMLCONTENT
    <style>
        .success {
            color: #fff;
            background-color: #4CAF50;
            padding: 10px;
            margin: 20px;
            border-radius: 5px;
            text-align: center;
            font-size: 16px;
        }
        .error {
            color: #D8000C;
            background-color: #FFD2D2;
            border: 1px solid #D8000C;
            margin: 20px;
            padding: 10px;
            border-radius: 5px;
            text-align: center;
            font-size: 18px;
        }
    </style>
    $message
HTMLCONTENT;

        $loginSection = $this->generateLoginSection();
        $this->html_page_content .= $loginSection;

        $moreStaticContent = <<<HTMLCONTENT
    </div>
    <div class="home-section-separator"></div>
HTMLCONTENT;
        $this->html_page_content .= $moreStaticContent;
        $this->html_page_output .= $this->html_page_content;
    }
    /**
     * Generates the HTML code for displaying the login section.
     *
     * @return string HTML code for displaying the login section.
     */
    private function generateLoginSection(): string
    {
        $registrationPromptHtml = <<<HTML
        <div style="margin-bottom: 20px;">
            <p>Don't have an account yet?</p>
            <a class="home-cta-btn Anchor button" href="/register" style="text-decoration: none; display: inline-block;">Register</a>
        </div>
HTML;
        // Additional button for navigating to the main page
        $mainPageButtonHtml = <<<HTML
    <div style="margin-top: 20px;">
        <a href="/" style="background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block;">Go to Main Page</a>
    </div>
HTML;
        // Adjust form action to "/login", method names, and IDs as necessary
        return <<<HTML
        <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
            <div style="text-align: center; width: 100%; max-width: 400px;">
                <h1 style="margin-bottom: 2rem; background-color: rgba(255, 255, 255, 0.8); padding: 1rem; border-radius: 8px;">User Login</h1>
                {$this->displayErrors()}
                <form action="/process_login" method="post" style="background: #f2f2f2; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                    <div style="margin-bottom: 1rem;">
                        <label for="login_username" style="display: block; margin-bottom: .5rem;">Email:</label>
                        <input type="text" id="login_username" name="email" required style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
                    </div>
                    <div style="margin-bottom: 1rem;">
                        <label for="login_password" style="display: block; margin-bottom: .5rem;">Password:</label>
                        <input type="password" id="login_password" name="password" required style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
                    </div>
                    <button type="submit" style="background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;">Login</button>
                    {$registrationPromptHtml}
                </form>
                            {$mainPageButtonHtml} <!-- This is the new button for going back to the main page -->

            </div>
        </div>
HTML;
    }
    // Inside LoginView.php
    /**
     * Displays login errors if any.
     *
     * @return string HTML code for displaying login errors.
     */
    protected function displayErrors() {
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        $errorsHtml = '';
        if (isset($_SESSION['login_errors']) && !empty($_SESSION['login_errors'])) {
            $errorsHtml = '<div class="error">';
            foreach ($_SESSION['login_errors'] as $error) {
                $errorsHtml .= "<p>$error</p>";
            }
            $errorsHtml .= '</div>';
            unset($_SESSION['login_errors']);
        }
        return $errorsHtml; // Return formatted errors or an empty string
    }

}